defaults: 
  - dataset: fc_abide2
  - model: hypergale   # hypergale,hypergraphgcn,hypergraphgcnv2,gcn,gat,graphsage
  - optimizer: adam
  - training: train

model: 
  model_save: False

log_path: result
repeat_time: 10
device: cuda:0

# wandb:
is_wandb: True
# doing_sweep: True
project: icassp
entity: mehular0ra
# sweep_id: asd-graph/asd-graph/r49h4avh



hydra:
  job_logging:
    root:
      handlers: [console, file]
      propagate: true
    formatters:
      precise:
        format: '[%(asctime)s][%(filename)s][L%(lineno)d][%(levelname)s]%(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: precise
        filename: ./output.log

